# We use the rust image as the base
# https://hub.docker.com/r/_/rust/
FROM rust:1.29.1

WORKDIR /usr/src/sammy

COPY . .

RUN cd folder && \
       cargo build --release && \
       cargo install --path . && \
       cargo clean

ENV RUST_LOG "folder=info"
ENV RUST_BACKTRACE 1

EXPOSE 8080

ENTRYPOINT ["folder"]
