# We use the rust image as the base
# https://hub.docker.com/r/_/rust/
FROM rust:1.29.1

WORKDIR /usr/src/sammy

COPY . .

RUN cd webserver && \
       cargo build --release && \
       cargo install --path . && \
       cargo clean

ENV RUST_LOG "webserver=info,actix_web=info"
ENV RUST_BACKTRACE 1

EXPOSE 8080

# Change our workdir to the webserver since that's where the html files are
WORKDIR /usr/src/sammy/webserver

ENTRYPOINT ["webserver"]
