# We use the rust image as the base
# https://hub.docker.com/r/_/rust/
FROM rust:1.29.0

WORKDIR /usr/src/sammy

COPY target/release/trade_history_migrate .

ENV RUST_LOG "trade_history_migrate=info"
ENV RUST_BACKTRACE 1

ENTRYPOINT ["trade_history_migrate"]
