# We use the rust image as the base
# https://hub.docker.com/r/_/rust/
FROM rust:1.29.0

WORKDIR /usr/src/sammy

COPY target/release/kraken_fetcher .

ENV RUST_LOG "kraken_fetcher=info"
ENV RUST_BACKTRACE 1

ENTRYPOINT ["kraken_fetcher"]
