# We use the rust image as the base
# https://hub.docker.com/r/_/rust/
FROM rust:1.29.0

WORKDIR /usr/src/sammy

COPY . .

RUN cd db/trade_history && \
		cargo build --release && \
		cargo install --path . && \
		cargo clean

ENV RUST_LOG "trade_history_migrate=info"
ENV RUST_BACKTRACE 1

CMD ["/usr/local/cargo/bin/trade_history_migrate"]
