# ---- Artifact Project Settings ----

# Paths containing artifact markdown/toml files
artifact_paths = ["design", "order_match_fetcher/design"]

# Paths to exclude when loading artifacts
exclude_artifact_paths = []

# Paths containing code that has artifact links
code_paths = ["order_match_fetcher/src"]

# Paths to exclude when searching through code
exclude_code_paths = []
