[package]
name = "common"
version = "0.1.0"
authors = ["Stephan Luther <kvsari@gmail.com>"]

[dependencies]
serde = "1.0.75"
serde_derive = "1.0.75"
rust_decimal = "0.10.1"
chrono = { version = "0.4.6", features = ["serde"] }
