#%RAML 1.0
---
title: translator API
version: v1
description: API defining write operations for insertion of new market data.
mediaType: application/json

/trade_match:
  get:
    description: Get a blurb about the type of data that is to be returned.
    responses:
      200:
        body:
          application/json:
            type: |
              {
                "type": "array",
                "$schema": "http://json-schema.org/draft-04/schema",
                "definitions": {
                  "item": {
                    "type": "object",
                    "properties": {
                      "assetpair": {"type":"string"},
                      "exchanges": {
                        "type":"array",
                        "elem":"string"
                      }
                    },
                    "required":["assetpair","exchanges"],
                    "additionalProperties":false
                  }
                },
                "properties": {
                  "items":{
                    "type":"array",
                    "elem":{"$ref":"#/definitions/item"}
                  }
                },
                "required": ["items"],
                "additionalProperties": false
              }
            example: |
              [{"assetpair":"btc/jpy", "exchanges":["kraken"]}]
  /{left_asset}:
    get:
      description: A listing of right side assets for this asset.
      responses:
        200:
          body:
            application/json:
              type: |
                {
                  "type": "array",
                  "$schema": "http://json-schema.org/draft-04/schema",
                  "properties": {
                    "items": {
                      "type":"array",
                      "elemt":"string"
                    }
                  },
                  "required":["items"],
                  "additionalProperties":false
                }
              example: |
                ["USD"]
    /{right_asset}:
      get:
        description: A listing of exchanges that this pair is being sourced from.
        responses:
          200:
            body:
              application/json:
                type: |
                  {
                    "type":"array",
                    "$schema": "http://json-schema.org/draft-04/schema",
                    "properties": {
                      "items": {
                        "type":"array",
                        "elemt":"string"
                      }
                    },
                    "required":["items"],
                    "additionalProperties":false
                  }
                example: |
                  ["kraken"]
      /{exchange}:
        post:
          description: Input new trade history data.
          body:
            application/json:
              type: |
                {
                  "type":"array",
                  "$schema": "http://json-schema.org/draft-04/schema",
                  "definitions": {
                    "match": {
                      "type":"object",
                      "properties": {
                        "timestamp": {
                          "type": "string",
                          "format": "datetime-only"
                        },
                        "size": {"type":"string"},
                        "price": {"type":"string"},
                        "market": {
                          "type":"string",
                          "enum":["maker", "taker"]
                        },
                        "meta": {"type":"string"}
                      },
                      "required":["size", "price", "market"],
                      "additionalProperties": false
                    }
                  },
                  "properties": {
                    "items": {
                      "type":"array",
                      "elem":{ "$ref":"#/definitions/match" }
                    }
                  }
                }
          responses:
            200:
              body:
                application/json:
                  type: |
                    {
                      "type":"array",
                      "$schema": "http://json-schema.org/draft-04/schema",
                      "definitions": {
                        "inserted": {
                          "type":"object",
                          "properties":{
                            "id": {"type":"integer"},
                            "timestamp": {
                              "type":"string",
                              "format":"datetime-only",
                              "description":"Time at which the record was stored."
                            }
                          },
                          "required":["id", "timestamp"],
                          "additionalProperties":false
                        },
                        "rejected": {
                          "type":"object",
                          "properties": {
                            "reason":{"type":"string"}
                          },
                          "required":["reason"],
                          "additionalProperties":false
                        }
                      },
                      "properties": {
                        "items": {
                          "type":"array",
                          "elem":{
                            "oneOf": [
                                { "$ref": "#/definitions/inserted" },
                                { "$ref": "#/definitions/rejected" }
                            ]
                          }
                        }
                      },
                      "required":["items"],
                      "additionalProperties":false
                    }
